import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";

import Providers from "./providers/providers";
import MenuAppBar from "./components/appbar/AppBar";

export const metadata: Metadata = {
  title: "Policia Chubut SRMP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Providers>
          <MenuAppBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
